.TH wallstreetcrawler 1

.SH NAME
wallstreetcrawler \- crawl through reddits and find wallstreet infos

.SH SYNOPSIS
.B wallstreetcrawler
[options] <parameters>

.SH DESCRIPTION
.PP 
\fIwallstreetcrawler\fP is a template project that actually does nothing.

.PP
\fIwallstreetcrawler\fP can be used as a template for the hard working real world applications.

.SH OPTIONS
.PP

available options and parameter for \fIwallstreetcrawler\fP are :

.TP
.BI \-\-version 
  show version and exit.
.TP
.BI \-\-help    
  show help and exit.

.SH RESOURCES
.PP
wallstreetcrawler uses almost no resources.

.SH DIAGNOSTICS
The program shouldn't do anything, so if it does something unexpected there's
probably something wrong. The return value is zero.

.SH SEE ALSO
The only other program we know with this this little functionality is the
ubiquitous hello world application.

.SH COPYRIGHT
wallstreetcrawler is copyright (c) 2025 ths <development@ths.one>.

This program is free software; you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation; either version 2 of the License, or
(at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program; if not, write to the Free Software
Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.

.SH BUGS
There probably are some, but we don't know what they are yet.

.SH AUTHORS
themurion@themurion.dev

.SH ACKNOWLEDGEMENT
thanks to all the countless people who contributed to this code by offering
their own code and knowlegde to the community.


